### ISSUE TITLE
Error using dev-setup script on Linux amd64

### ISSUE THREAD

**Issue by PrimaIVoid** [spicelang/spice#376]
When running `./dev-setup` on my Linux amd64 i receive the following error (relevant part):

```
 Looking for dladdr
-- Looking for dladdr - found
-- Looking for proc_pid_rusage
-- Looking for proc_pid_rusage - not found
-- Performing Test HAVE_CXX_ATOMICS_WITHOUT_LIB
-- Performing Test HAVE_CXX_ATOMICS_WITHOUT_LIB - Failed
-- Looking for __atomic_fetch_add_4 in atomic
-- Looking for __atomic_fetch_add_4 in atomic - found
-- Performing Test HAVE_CXX_ATOMICS_WITH_LIB
-- Performing Test HAVE_CXX_ATOMICS_WITH_LIB - Failed
CMake Error at cmake/modules/CheckAtomic.cmake:56 (message):
  Host compiler must support std::atomic!
Call Stack (most recent call first):
  cmake/config-ix.cmake:418 (include)
  CMakeLists.txt:868 (include)

-- Configuring incomplete, errors occurred!
See also "/home/zodiac/spice/llvm/build-release/CMakeFiles/CMakeOutput.log".
See also "/home/zodiac/spice/llvm/build-release/CMakeFiles/CMakeError.log".
ninja: error: loading 'build.ninja': No such file or directory
done.
[Step 4] Downloading third-party libraries ... 
done.
[Step 5] Building Spice ... 
done.
The setup is done. Have fun coding!
Whenever you need to build Spice again, use the ./build.sh script.
```
Is also worth to add that the script goes on until is finished with all the required steps even though it encountered an error. It should probably quit after hitting an error

Full Log files added
[CMakeError.log](https://github.com/spicelang/spice/files/13365443/CMakeError.log)
[CMakeOutput.log](https://github.com/spicelang/spice/files/13365444/CMakeOutput.log)

**Comment by marcauberer** [comment]
Hi @PrimaIVoid! It seems like you need to install a newer C++ compiler. The output above is from the LLVM build.

>It should probably quit after hitting an error
I agree. Will fix this one.

**Comment by marcauberer** [comment]
Which C++ compiler do you use?

**Comment by PrimaIVoid** [comment]
> Which C++ compiler do you use?

gcc version 13.1.0 (Ubuntu 13.1.0-8ubuntu1~22.04)

**Comment by marcauberer** [comment]
I know what the problem is. The dev-setup script is using the lld linker, which seems not to be installed.
Maybe we should not rely that the lld linker is installed and use the default linker.

**Comment by PrimaIVoid** [comment]
I've seen this `std::atomic` error in other languages too when switching from different gcc versions, i think they removed/moved it and that creates incompatibilities

Anyhow on my system i have also installed gcc 11 and gcc 12, they are both available so i might try to switch to gcc 12 and try to rebuild and see if that works (probably it will do). Of course that is not a real fix

**Comment by marcauberer** [comment]
>FAILED: cmTC_a95bc 
: && /usr/bin/g++ -std=c++11 -O2 -fuse-ld=lld  CMakeFiles/cmTC_a95bc.dir/src.cxx.o -o cmTC_a95bc  -lm  -latomic && :
collect2: fatal error: cannot find ‘ld’
compilation terminated.
ninja: build stopped: subcommand failed.

From this error I deduce, that lld is not installed on your system. I adapted the scripts so that lld is installed in the first step of the script. The fixed script is on the main branch now. Can you try it out if it works now?

**Comment by PrimaIVoid** [comment]
The new script now noticed the missing dependency and prompt to install it:
```
The following additional packages will be installed:
  lld-14
The following NEW packages will be installed:
  lld lld-14
```
After installing it the building continued with the LLVM and was all ok

**Comment by marcauberer** [comment]
Alright, thanks for reporting!
