### ISSUE TITLE
Improve compiler '-version' info

### ISSUE THREAD

**Issue by PrimaIVoid** [spicelang/spice#418]
Some compiler output i've seen in other programming languages could be added to Spice too:

On terminal the command `spice` can be an alias for `spice -help` instead of as it work right: an unrecognized command

On terminal `spice -v` should also print the current system specific version (aka if the current active installed compiler is `linux_amd64` or `linux_arm64` or others)

Eventually if in the future the Spice compiler will have a `dev` and `stable` branch/releases, show that info with `spice -v` too

**Comment by marcauberer** [comment]
Hi @PrimaIVoid!

>On terminal the command spice can be an alias for spice -help instead of as it work right: an unrecognized command
I also had the idea, but didn't do it so far.

>On terminal spice -v should also print the current system specific version
We can do that. That shouldn't be that big of a problem.

>Eventually if in the future the Spice compiler will have a dev and stable branch/releases
In fact the `-v` flag already shows `dev` when you build the Spice compiler yourself on a dev machine. For stable builds, only the version number e.g. `0.19.0` is currently displayed.

I will prepare a change to adjust the things you pointed out. Thanks for helping!
